/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;



       



/**
 *
 * @author arjarma
 */
public class NewJFrame_1 extends javax.swing.JFrame {
      Connection conn=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    Statement stmt=null;
    Statement stmt1=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame_1() {
        initComponents();
    }

public void select()
{
    String sql="select * from studentdata where Enrollment_No='"+enrolltf.getText()+"';";
     try
        {
          //datastd ds=new datastd();
          //ds.setVisible(true);
          //setVisible(false);
        
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","arjarma");
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            while(rs.next())
            {   enrolltf.setText(rs.getString(1));
                nametf.setText(rs.getString(2));
                fnametf.setText(rs.getString(3));
                addresstf.setText(rs.getString(4));
                dobtf.setText(rs.getString(5));                
                gender.setSelectedItem(rs.getString(6));
                emailtf.setText(rs.getString(7));
                branch.setSelectedItem(rs.getString(8));
                dept.setSelectedItem(rs.getString(9));
                batch.setSelectedItem(rs.getString(10));
                semester.setSelectedItem(rs.getString(11));
                cgpatf.setText(rs.getString(12));
                mobiletf.setText(rs.getString(13));
            }
            
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Something went wrong::RE TRY");
            
        }
}

public void uneditable()
{
    
    nametf.setEditable(false);
    fnametf.setEditable(false);
    addresstf.setEditable(false);
    cgpatf.setEditable(false);
    gender.setEditable(false);
    emailtf.setEditable(false);
    branch.setEditable(false);
    batch.setEditable(false);
    semester.setEditable(false);
    mobiletf.setEditable(false);
    dobtf.setEditable(false);
    dept.setEditable(false);
}
 public void refreshFrame()
 {
     NewJFrame_1 njf1=new NewJFrame_1();
            njf1.setVisible(true);
            setVisible(false);
 }
 public void refreshTable(){
     datastd ds = new datastd();
     ds.setVisible(true);
     setVisible(false);
     
 }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        mysqlPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("mysqlPU").createEntityManager();
        studentdataQuery = java.beans.Beans.isDesignTime() ? null : mysqlPUEntityManager.createQuery("SELECT s FROM Studentdata s");
        studentdataList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : studentdataQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        enrolltf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        fnametf = new javax.swing.JTextField();
        mobiletf = new javax.swing.JTextField();
        addresstf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        cgpatf = new javax.swing.JTextField();
        dept = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        branch = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        viewbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        insertbtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        loadbtn = new javax.swing.JButton();
        dobtf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        gender = new javax.swing.JComboBox<>();
        batch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT DATA OPERATION WINDOW ");
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(1200, 1100));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 1000));
        setSize(new java.awt.Dimension(900, 900));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText(" STUDENT DATA  OPERATIONS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 310, 30);

        jLabel2.setText("Enrollment_No");

        jLabel3.setText("Name");

        jLabel4.setText("Fathers_Name");

        jLabel5.setText("Address");

        jLabel6.setText("Mobile_No");

        jLabel7.setText("DOB");

        enrolltf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        enrolltf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrolltfActionPerformed(evt);
            }
        });

        nametf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        fnametf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fnametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametfActionPerformed(evt);
            }
        });

        mobiletf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        addresstf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setText("Email_ID");

        jLabel10.setText("Batch");

        jLabel11.setText("Branch");

        jLabel12.setText("CGPA");

        jLabel13.setText("Semester");

        jLabel14.setText("Department");

        emailtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emailtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtfActionPerformed(evt);
            }
        });

        cgpatf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cgpatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpatfActionPerformed(evt);
            }
        });

        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ASE", "ASET", " " }));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });

        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "01", "02", "03", "04", "05", "06", "07", "08" }));
        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });

        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CSE", "IT", "MAE", "CIVIL", "ECE", "AEROSPACE" }));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        viewbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewbtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468285491_magnifyingglass.png")); // NOI18N
        viewbtn.setText("VIEW STUDENT DATA");
        viewbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468285444_Remove-Male-User.png")); // NOI18N
        deletebtn.setText("DELETE STUDENT DATA");
        deletebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updtbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updtbtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468285371_gtk-refresh.png")); // NOI18N
        updtbtn.setText("UPDATE STUDENT DATA");
        updtbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468285587_history-clear.png")); // NOI18N
        clearbtn.setText("CLEAR");
        clearbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468284991_common-logout-signout-exit-glyph.png")); // NOI18N
        exitbtn.setText("EXIT");
        exitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        insertbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertbtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468284956_insert-object.png")); // NOI18N
        insertbtn.setText("ADD STUDENT DATA");
        insertbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        refreshbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refreshbtn.setIcon(new javax.swing.ImageIcon("E:\\arma Project\\Icons\\1468284923_view-refresh.png")); // NOI18N
        refreshbtn.setText("REFRESH");
        refreshbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        loadbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loadbtn.setText("LOAD DATA");
        loadbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        loadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deletebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updtbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(loadbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updtbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(loadbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(clearbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dobtf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setText("Gender");

        StudentTable.setBackground(new java.awt.Color(255, 102, 102));
        StudentTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        StudentTable.setMinimumSize(new java.awt.Dimension(1031, 561));
        StudentTable.setName("StudentData"); // NOI18N
        StudentTable.setPreferredSize(new java.awt.Dimension(1031, 561));
        StudentTable.setSelectionForeground(new java.awt.Color(0, 0, 255));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, studentdataList, StudentTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${enrollmentNo}"));
        columnBinding.setColumnName("Enrollment No");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fathersName}"));
        columnBinding.setColumnName("Fathers Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dob}"));
        columnBinding.setColumnName("Dob");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${gender}"));
        columnBinding.setColumnName("Gender");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailid}"));
        columnBinding.setColumnName("Emailid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${branch}"));
        columnBinding.setColumnName("Branch");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${department}"));
        columnBinding.setColumnName("Department");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${batch}"));
        columnBinding.setColumnName("Batch");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${semester}"));
        columnBinding.setColumnName("Semester");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cgpa}"));
        columnBinding.setColumnName("Cgpa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mobileNo}"));
        columnBinding.setColumnName("Mobile No");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        jScrollPane1.setViewportView(StudentTable);

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));

        batch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2006\t", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailtf, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(enrolltf)
                    .addComponent(nametf)
                    .addComponent(fnametf)
                    .addComponent(addresstf)
                    .addComponent(mobiletf)
                    .addComponent(dobtf))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dept, 0, 100, Short.MAX_VALUE)
                                    .addComponent(semester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cgpatf, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(batch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enrolltf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cgpatf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(fnametf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addresstf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobiletf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 21, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void cgpatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgpatfActionPerformed

    private void fnametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametfActionPerformed

    private void emailtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtfActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        nametf.setText(" ");
        enrolltf.setText(" ");
        fnametf.setText(" ");
        mobiletf.setText(" ");
        addresstf.setText(" ");
        emailtf.setText(" ");
        batch.setSelectedIndex(0);
        cgpatf.setText(" ");
        dept.setSelectedIndex(0);
        semester.setSelectedIndex(0);
        branch.setSelectedIndex(0);
        dobtf.setText(" ");
        gender.setSelectedIndex(0);
        uneditable();
        enrolltf.setEditable(false);

    }//GEN-LAST:event_clearbtnActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        
        String Enrollment_No,Name,Fathers_Name,Address,Dob,Gender,Email_id,Branch,Department,Batch,Semester,Cgpa,Mobile_No;
        //String sql= "INSERT INTO studentdata(Enrollment_No,Name,Fathers_Name,Address,Dob,Gender,Emailid,Branch,Department,Batch,Semester,Cgpa,Mobile_No) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?);";
        String sql= "INSERT INTO studentdata(Enrollment_No,Name,Fathers_Name,Address,Dob,Gender,Email_id,Branch,Department,Batch,Semester,Cgpa,Mobile_No) VALUES('"+
enrolltf.getText()+"','"+nametf.getText()+"','"+fnametf.getText()+"','"+addresstf.getText()+"','"+dobtf.getText()+"','"+gender.getSelectedItem().toString()+"','"+emailtf.getText()+"','"+branch.getSelectedItem().toString()+"','"+dept.getSelectedItem().toString()+"','"+batch.getSelectedItem().toString()+"','"+semester.getSelectedItem().toString()+"','"+cgpatf.getText()+"','"+mobiletf.getText()+"');";
        int ans=JOptionPane.showConfirmDialog(null,"You want to insert data?");
        if(ans==JOptionPane.YES_OPTION)
        {
        try
        {
            
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","arjarma");
            pst=conn.prepareStatement(sql);
           
            pst.execute();
        
        nametf.setText(" ");
        enrolltf.setText(" ");
        fnametf.setText(" ");
        mobiletf.setText(" ");
        addresstf.setText(" ");
        emailtf.setText(" ");
        batch.setSelectedIndex(0);
        cgpatf.setText(" ");
        dept.setSelectedIndex(0);
        semester.setSelectedIndex(0);
        branch.setSelectedIndex(0);
        dobtf.setText(" ");
        gender.setSelectedIndex(0);
        JOptionPane.showMessageDialog(null,"Data Inserted Successfully In Table");
            refreshTable();  
        } 
        
        
        catch(SQLException | HeadlessException ex)
        {
            JOptionPane.showMessageDialog(null,"Wrong Data Entry::Try Again");
            refreshFrame();
        }
        } 
        //JOptionPane.showMessageDialog(null,"Data Inserted Successfully In Table");
            //refreshTable();
        
         
    }//GEN-LAST:event_insertbtnActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
    String sql="select * from studentdata;";
     try
        {
            uneditable();
            enrolltf.setEditable(false);
          //refreshFrame();
          
        
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","arjarma");
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                rs.getString(1);
                rs.getString(2);
                rs.getString(3);
                rs.getString(4);                
                rs.getString(5);
                rs.getString(6);
                rs.getString(7);
                rs.getString(8);
                rs.getString(9);
                rs.getString(10);
                rs.getString(11);
                rs.getString(12);
                rs.getString(13);
           
            }
            JOptionPane.showMessageDialog(null,"Have A Look"); 
           
            refreshTable();
             JOptionPane.showMessageDialog(null,"Total Records Available are:"+StudentTable.getRowCount());
         }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Something went wrong::TRY AGAIN");
            
        }
    }//GEN-LAST:event_viewbtnActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        
        String Enrollment_No,Name,Fathers_Name,Address,Dob,Gender,Email_id,Branch,Department,Batch,Semester,Cgpa,Mobile_No;             
       String query="UPDATE studentdata SET Name='"+nametf.getText()+"',Fathers_Name='"+fnametf.getText()+"',Address='"+addresstf.getText()+"',Dob='"+dobtf.getText()+"',Gender='"+gender.getSelectedItem().toString()+"',Email_id='"+emailtf.getText()+"',Branch='"+branch.getSelectedItem().toString()+"',Department='"+dept.getSelectedItem().toString()+"',Batch='"+batch.getSelectedItem().toString()+"',Semester='"+semester.getSelectedItem().toString()+"',Cgpa='"+cgpatf.getText()+"',Mobile_No='"+mobiletf.getText()+"' WHERE Enrollment_No='"+enrolltf.getText()+"';"; 
       String sql="select * from studentdata where Enrollment_No='"+enrolltf.getText()+"';";
       
       try
        {
            
        
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","arjarma");
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
           pst=conn.prepareStatement(query);
           pst.execute(query); 
           
            
           while(rs.next())
            {  
                enrolltf.setText(rs.getString(1));
                nametf.setText(rs.getString(2));
                fnametf.setText(rs.getString(3));
                addresstf.setText(rs.getString(4));
                dobtf.setText(rs.getString(5));                
                gender.setSelectedItem(rs.getString(6));
                emailtf.setText(rs.getString(7));
                branch.setSelectedItem(rs.getString(8));
                dept.setSelectedItem(rs.getString(9));
                batch.setSelectedItem(rs.getString(10));
                semester.setSelectedItem(rs.getString(11));
                cgpatf.setText(rs.getString(12));
                mobiletf.setText(rs.getString(13));
                
            } 
              
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Wrong Data Entry");
            refreshFrame();
            
        }
        
    }//GEN-LAST:event_updtbtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
       refreshFrame();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       
        
        String Enrollment_No,Name,Fathers_Name,Address,Dob,Gender,Email_id,Branch,Department,Batch,Semester,Cgpa,Mobile_No;             
        
        refreshFrame();
    nametf.setEditable(false);
    fnametf.setEditable(false);
    addresstf.setEditable(false);
    cgpatf.setEditable(false);
    gender.setEditable(false);
    emailtf.setEditable(false);
    branch.setEditable(false);
    batch.setEditable(false);
    semester.setEditable(false);
    mobiletf.setEditable(false);
    dobtf.setEditable(false);
    dept.setEditable(false);
        
        //int ans;
        //ans=JOptionPane.showConfirmDialog(null,"Do You Want To Delete The Data?");
        String sql="Delete FROM studentdata Where Enrollment_No='"+enrolltf.getText()+"';";
        
        try{
        
          
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","arjarma");
            pst=conn.prepareStatement(sql);
            pst.executeUpdate(sql);
            
            refreshTable();
            //refreshFrame();
        JOptionPane.showMessageDialog(null,"Row Deleted Successful");
        
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Wrong Data Entry::Try Again");
        }
        
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void loadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbtnActionPerformed
       select();
       updtbtn.setEnabled(true);
       uneditable();
       enrolltf.setEditable(false);
       //uneditable();
       //enrolltf.setEditable(false);
    }//GEN-LAST:event_loadbtnActionPerformed

    private void enrolltfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrolltfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrolltfActionPerformed
    
        
    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentTable;
    private javax.swing.JTextField addresstf;
    private javax.swing.JComboBox<String> batch;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.JTextField cgpatf;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JTextField dobtf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField enrolltf;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField fnametf;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadbtn;
    private javax.swing.JTextField mobiletf;
    private javax.persistence.EntityManager mysqlPUEntityManager;
    private javax.swing.JTextField nametf;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JComboBox<String> semester;
    private java.util.List<student.Studentdata> studentdataList;
    private javax.persistence.Query studentdataQuery;
    private javax.swing.JButton updtbtn;
    private javax.swing.JButton viewbtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void values(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
